Add shuffle option

diff --git a/wgnord b/wgnord
--- a/wgnord
+++ b/wgnord
@@ -5,16 +5,16 @@ alias print_error="printf \"\033[31m%s\n\033[0m\""
 host="api.nordvpn.com"
 conf_dir=/var/lib/wgnord
 check_root() {
-	if [ "$(id -u)" -ne 0 ]; then
-		echo "This script must be run as root"
-		exit 1
-	fi
+    if [ "$(id -u)" -ne 0 ]; then
+        echo "This script must be run as root"
+        exit 1
+    fi
 }
 login() {
-	[ -z "$1" ] && help
-	auth_token="$(printf "%s" "token:$1" | base64 -w 0)"
-	query "https://$host/v1/users/services/credentials" -H "Content-Type: application/json" -H "Authorization: Basic $auth_token" > $conf_dir/credentials.json
-	err="$(jq -er '.errors.message' $conf_dir/credentials.json)" && { print_error "Error getting credentials: $err"; exit 1; }
+    [ -z "$1" ] && help
+    auth_token="$(printf "%s" "token:$1" | base64 -w 0)"
+    query "https://$host/v1/users/services/credentials" -H "Content-Type: application/json" -H "Authorization: Basic $auth_token" > $conf_dir/credentials.json
+    err="$(jq -er '.errors.message' $conf_dir/credentials.json)" && { print_error "Error getting credentials: $err"; exit 1; }
 }
 get_country_code() {
     buf="$(grep -i "^$1	" -m 1 $conf_dir/countries_iso31662.txt | cut -d "	" -f 2)"
@@ -22,51 +22,55 @@ get_country_code() {
     echo "$buf"
 }
 connect() {
-	out_file=/etc/wireguard/wgnord.conf
-	OPTIND=2
-	while getopts "fno:" o; do case "$o" in
-		f) force=1 ;;
-		n) dont_act=1 ;;
-		o) out_file="$OPTARG" ;;
-		*) exit 1 ;;
-	esac done
-	[ -z "$1" ] && help
-	print "Finding best server..."
-	if [ $force ] || [ ! -f $conf_dir/coords.json ] && [ ! $dont_act ]; then
-		is_connected && disconnect
-		insights="$(query "https://$host/v1/helpers/ips/insights")"
-		longitude="$(echo "$insights" | jq -j '.longitude')"
-		latitude="$(echo "$insights" | jq -j '.latitude')"
-		jq -njc "{longitude: $longitude, latitude: $latitude}" > $conf_dir/coords.json
-	else
-		longitude="$(jq -er '.longitude' $conf_dir/coords.json)"
-		latitude="$(jq -er '.latitude' $conf_dir/coords.json)"
-	fi
-	country_code="$(get_country_code "$1")"
-	recommendations="$(query "https://$host/v1/servers/recommendations?limit=20&filters%5Bservers.status%5D=online&filters%5Bservers_technologies%5D=35&filters%5Bservers_technologies%5D%5Bpivot%5D%5Bstatus%5D=online&fields%5Bservers.id%5D&fields%5Bservers.name%5D&fields%5Bservers.hostname%5D&fields%5Bservers.station%5D&fields%5Bservers.status%5D&fields%5Bservers.load%5D&fields%5Bservers.created_at%5D&fields%5Bservers.groups.id%5D&fields%5Bservers.groups.title%5D&fields%5Bservers.technologies.id%5D&fields%5Bservers.technologies.metadata%5D&fields%5Bservers.technologies.pivot.status%5D&fields%5Bservers.specifications.identifier%5D&fields%5Bservers.specifications.values.value%5D&fields%5Bservers.locations.country.name%5D&fields%5Bservers.locations.country.code%5D&fields%5Bservers.locations.country.city.name%5D&fields%5Bservers.locations.country.city.latitude%5D&fields%5Bservers.locations.country.city.longitude%5D&coordinates%5Blongitude%5D=$longitude&coordinates%5Blatitude%5D=$latitude&fields%5Bservers.ips%5D&filters%5Bcountry_id%5D=$country_code")"
-	server_name="$(echo "$recommendations" | jq -j '.[0] | .name')"
-	server_hostname="$(echo "$recommendations" | jq -j '.[0] | .hostname')"
-	server_ip="$(echo "$recommendations" | jq -j '.[0] | .ips[0].ip.ip')"
-	server_pubkey="$(echo "$recommendations" | jq -j '.[0] | .technologies[] | select(.metadata[0].name == "public_key") | .metadata[0].value')"
-	privkey="$(jq -j '.nordlynx_private_key' $conf_dir/credentials.json)"
-	sed -e "s|PRIVKEY|$privkey|" -e "s|SERVER_PUBKEY|$server_pubkey|" -e "s|SERVER_IP|$server_ip|" $conf_dir/template.conf > "$out_file"
-	if [ ! $dont_act ]; then
-		print "Connecting to $server_hostname ($server_name)..."
-		if is_connected; then
-			wg-quick strip wgnord | wg setconf wgnord /dev/stdin
-			wg set wgnord fwmark 0xca6c
-		else
-			wg-quick up wgnord
-		fi && print "Connected successfully!"
-	fi
+    out_file=/etc/wireguard/wgnord.conf
+    OPTIND=2
+    while getopts "fnso:" o; do case "$o" in
+        f) force=1 ;;
+        n) dont_act=1 ;;
+        s) shuf=1 ;;
+        o) out_file="$OPTARG" ;;
+        *) exit 1 ;;
+    esac done
+    [ -z "$1" ] && help
+    print "Finding best server..."
+    if [ $force ] || [ ! -f $conf_dir/coords.json ] && [ ! $dont_act ]; then
+        is_connected && disconnect
+        insights="$(query "https://$host/v1/helpers/ips/insights")"
+        longitude="$(echo "$insights" | jq -j '.longitude')"
+        latitude="$(echo "$insights" | jq -j '.latitude')"
+        jq -njc "{longitude: $longitude, latitude: $latitude}" > $conf_dir/coords.json
+    else
+        longitude="$(jq -er '.longitude' $conf_dir/coords.json)"
+        latitude="$(jq -er '.latitude' $conf_dir/coords.json)"
+    fi
+    country_code="$(get_country_code "$1")"
+    recommendations="$(query "https://$host/v1/servers/recommendations?limit=20&filters%5Bservers.status%5D=online&filters%5Bservers_technologies%5D=35&filters%5Bservers_technologies%5D%5Bpivot%5D%5Bstatus%5D=online&fields%5Bservers.id%5D&fields%5Bservers.name%5D&fields%5Bservers.hostname%5D&fields%5Bservers.station%5D&fields%5Bservers.status%5D&fields%5Bservers.load%5D&fields%5Bservers.created_at%5D&fields%5Bservers.groups.id%5D&fields%5Bservers.groups.title%5D&fields%5Bservers.technologies.id%5D&fields%5Bservers.technologies.metadata%5D&fields%5Bservers.technologies.pivot.status%5D&fields%5Bservers.specifications.identifier%5D&fields%5Bservers.specifications.values.value%5D&fields%5Bservers.locations.country.name%5D&fields%5Bservers.locations.country.code%5D&fields%5Bservers.locations.country.city.name%5D&fields%5Bservers.locations.country.city.latitude%5D&fields%5Bservers.locations.country.city.longitude%5D&coordinates%5Blongitude%5D=$longitude&coordinates%5Blatitude%5D=$latitude&fields%5Bservers.ips%5D&filters%5Bcountry_id%5D=$country_code")"
+    if [ $shuf ]; then
+        recommendations="$(echo "$recommendations" | jq -c '.[]' | shuf | jq -s '.')"
+    fi
+    server_name="$(echo "$recommendations" | jq -j '.[0] | .name')"
+    server_hostname="$(echo "$recommendations" | jq -j '.[0] | .hostname')"
+    server_ip="$(echo "$recommendations" | jq -j '.[0] | .ips[0].ip.ip')"
+    server_pubkey="$(echo "$recommendations" | jq -j '.[0] | .technologies[] | select(.metadata[0].name == "public_key") | .metadata[0].value')"
+    privkey="$(jq -j '.nordlynx_private_key' $conf_dir/credentials.json)"
+    sed -e "s|PRIVKEY|$privkey|" -e "s|SERVER_PUBKEY|$server_pubkey|" -e "s|SERVER_IP|$server_ip|" $conf_dir/template.conf > "$out_file"
+    if [ ! $dont_act ]; then
+        print "Connecting to $server_hostname ($server_name)..."
+        if is_connected; then
+            wg-quick strip wgnord | wg setconf wgnord /dev/stdin
+            wg set wgnord fwmark 0xca6c
+        else
+            wg-quick up wgnord
+        fi && print "Connected successfully!"
+    fi
 }
 disconnect() {
-	print "Disconnecting..."
-	wg-quick down wgnord
+    print "Disconnecting..."
+    wg-quick down wgnord
 }
 is_connected() {
-	ip link show wgnord > /dev/null 2>&1
-	return
+    ip link show wgnord > /dev/null 2>&1
+    return
 }
 help() { cat << EOF
 Usage: wgnord [ l(ogin) | c(onnect) | d(isconnect) ]
@@ -78,18 +82,19 @@ connect:
     wgnord c france
     -f            Refresh cached longitude/latitude
     -n            Don't connect
+    -s            Shuffle recommendations list before connecting
     -o out.conf   Write config to different file
 disconnect:
     wgnord d
 
 wgnord's files are in $conf_dir, edit template.conf to change Wireguard options
 EOF
-	exit
+    exit
 }
 
 case $1 in
-	l|login) check_root; login "$2" ;;
-	c|connect) check_root; shift; connect "$@" ;;
-	d|disconnect) check_root; disconnect ;;
-	*) help ;;
+    l|login) check_root; login "$2" ;;
+    c|connect) check_root; shift; connect "$@" ;;
+    d|disconnect) check_root; disconnect ;;
+    *) help ;;
 esac
